on: [pull_request, push]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        node-version: [16.x, 17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test go
        run: go test -race ./...
      - run: npm install
        working-directory: ./web
      - run: npm run build --if-present
        working-directory: ./web
      - run: npm test
        working-directory: ./web
        env:
          CI: true
